# -*- coding: utf-8 -*-
"""SpeechRecognition(finalProject).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IkIpfoivGNf0OmFINGGlOvZCwg-2iNXx
"""

!pip install librosa tensorflow gradio seaborn kagglehub soundfile scikit-learn

import os
import numpy as np
import pandas as pd
import librosa
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import warnings
import kagglehub
import soundfile as sf
import gradio as gr

from tqdm import tqdm
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.utils.class_weight import compute_class_weight

from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Model
from tensorflow.keras.layers import *
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

warnings.filterwarnings("ignore")
print("TensorFlow:", tf.__version__)
print("All libraries imported successfully!")

# ================= Visualization Style =================
plt.style.use("seaborn-v0_8-whitegrid")
sns.set_context("talk")
sns.set_palette("Set2")

FIGSIZE = (8, 6)
DPI = 120

path = kagglehub.dataset_download("uwrfkaggler/ravdess-emotional-speech-audio")
print("Dataset path:", path)
DATASET_PATH = path

emotion_map = {
    '01': 'neutral', '02': 'calm', '03': 'happy', '04': 'sad',
    '05': 'angry', '06': 'fearful', '07': 'disgust', '08': 'surprised'
}

file_paths, emotions, actors = [], [], []
for root, dirs, files in os.walk(DATASET_PATH):
    for fname in files:
        if fname.endswith(".wav"):
            parts = fname.split("-")
            if len(parts) >= 7:
                emo_code = parts[2]
                actor = int(parts[-1].split(".")[0])
                emotion = emotion_map.get(emo_code)
                if emotion:
                    file_paths.append(os.path.join(root, fname))
                    emotions.append(emotion)
                    actors.append(actor)

data = pd.DataFrame({
    "file_path": file_paths,
    "emotion": emotions,
    "actor": actors
})
data["gender"] = data["actor"].apply(lambda x: "male" if x % 2 == 1 else "female")

print("Data loaded successfully:")
print(data.head())
print(f"Total samples: {len(data)}")
# ================= Dataset Emotion Distribution =================
plt.figure(figsize=(8, 6), dpi=120)
sns.countplot(
    data=data,
    x="emotion",
    order=data["emotion"].value_counts().index
)
plt.title("Emotion Distribution in RAVDESS Dataset")
plt.xlabel("Emotion")
plt.ylabel("Number of Samples")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()


SAMPLE_RATE = 22050
DURATION = 3.0
N_MFCC = 40
N_MELS = 128
HOP_LENGTH = 512
N_FFT = 2048
MAX_LEN = 216

def preprocess_audio(path):
    y, sr = librosa.load(path, sr=SAMPLE_RATE, duration=DURATION)
    y, _ = librosa.effects.trim(y)
    if np.max(np.abs(y)) > 0:
        y = y / np.max(np.abs(y))
    target_len = int(SAMPLE_RATE * DURATION)
    if len(y) < target_len:
        y = np.pad(y, (0, target_len - len(y)))
    else:
        y = y[:target_len]
    return y, sr

def extract_features(path):
    """
    Extract comprehensive audio features:
    MFCCs, Delta, Delta-Delta, Log-Mel Spectrogram,
    Chroma, Spectral Contrast, Pitch, and Energy (RMS)
    """
    # Preprocess audio
    y, sr = preprocess_audio(path)

    # ========== MFCC Features ==========
    mfcc = librosa.feature.mfcc(
        y=y,
        sr=sr,
        n_mfcc=N_MFCC,
        hop_length=HOP_LENGTH
    )
    mfcc_d = librosa.feature.delta(mfcc)
    mfcc_dd = librosa.feature.delta(mfcc, order=2)

    # ========== Log-Mel Spectrogram ==========
    mel = librosa.feature.melspectrogram(
        y=y,
        sr=sr,
        n_mels=N_MELS,
        hop_length=HOP_LENGTH,
        n_fft=N_FFT
    )
    logmel = librosa.power_to_db(mel)

    # ========== Chroma Features ==========
    chroma = librosa.feature.chroma_stft(
        y=y,
        sr=sr,
        hop_length=HOP_LENGTH,
        n_fft=N_FFT
    )

    # ========== Spectral Contrast ==========
    contrast = librosa.feature.spectral_contrast(
        y=y,
        sr=sr,
        hop_length=HOP_LENGTH,
        n_fft=N_FFT
    )

    # ========== Pitch (Fundamental Frequency) ==========
    pitch = librosa.yin(
        y,
        fmin=50,
        fmax=300,
        sr=sr
    )
    pitch = pitch.reshape(1, -1)

    # ========== Energy (RMS) ==========
    energy = librosa.feature.rms(
        y=y,
        hop_length=HOP_LENGTH
    )

    # ========== Combine All Features ==========
    features = np.vstack([
        mfcc,
        mfcc_d,
        mfcc_dd,
        logmel,
        chroma,
        contrast,
        pitch,
        energy
    ])

    return features
print("Extracting features... (This may take a while)")
features = []
for _, row in tqdm(data.iterrows(), total=len(data)):
    feat = extract_features(row.file_path)
    features.append(feat)

print("Padding and reshaping features...")
X_raw = []
for f in features:
    if f.shape[1] < MAX_LEN:
        pad = MAX_LEN - f.shape[1]
        f = np.pad(f, ((0,0),(0,pad)), mode='constant')
    else:
        f = f[:, :MAX_LEN]
    X_raw.append(f)

X_raw = np.array(X_raw, dtype=np.float32)
X = X_raw.reshape(X_raw.shape[0], X_raw.shape[1], X_raw.shape[2], 1)

scaler = StandardScaler()
X_flat = X.reshape(X.shape[0], -1)
X_scaled = scaler.fit_transform(X_flat)
X = X_scaled.reshape(X.shape)

print("Feature extraction and scaling complete!")
print("Final shape for model input:", X.shape)

emotions_list = sorted(set(data["emotion"]))
gender_list = sorted(set(data["gender"]))
speaker_list = sorted(set(data["actor"]))

y_emotion = np.array([emotions_list.index(i) for i in data["emotion"]])
y_gender = np.array([gender_list.index(i) for i in data["gender"]])
y_speaker = np.array([speaker_list.index(i) for i in data["actor"]])

# Get original indices for splitting
indices = np.arange(len(X))

# Split indices into train, temp (for val/test)
train_idx, temp_idx, _, _, _, _, _, _ = train_test_split(
    indices, y_emotion, y_gender, y_speaker, test_size=0.3, stratify=y_emotion, random_state=42
)

# Split temp_idx into val, test
val_idx, test_idx, _, _, _, _, _, _ = train_test_split(
    temp_idx, y_emotion[temp_idx], y_gender[temp_idx], y_speaker[temp_idx], test_size=0.5, stratify=y_emotion[temp_idx], random_state=42
)

# Apply indices to X and y arrays
X_train, X_val, X_test = X[train_idx], X[val_idx], X[test_idx]
y_train_emotion, y_val_emotion, y_test_emotion = y_emotion[train_idx], y_emotion[val_idx], y_emotion[test_idx]
y_train_gender, y_val_gender, y_test_gender = y_gender[train_idx], y_gender[val_idx], y_gender[test_idx]
y_train_speaker, y_val_speaker, y_test_speaker = y_speaker[train_idx], y_speaker[val_idx], y_speaker[test_idx]

# Extract file paths for training, validation, and test sets
paths_train = data["file_path"].iloc[train_idx].values
paths_val = data["file_path"].iloc[val_idx].values
paths_test = data["file_path"].iloc[test_idx].values


y_train_emotion_oh = to_categorical(y_train_emotion)
y_val_emotion_oh = to_categorical(y_val_emotion)
y_test_emotion_oh = to_categorical(y_test_emotion)

y_train_gender_oh = to_categorical(y_train_gender)
y_val_gender_oh = to_categorical(y_val_gender)
y_test_gender_oh = to_categorical(y_test_gender)

y_train_speaker_oh = to_categorical(y_train_speaker)
y_val_speaker_oh = to_categorical(y_val_speaker)
y_test_speaker_oh = to_categorical(y_test_speaker)


print(f"Data split: Train={len(X_train)}, Val={len(X_val)}, Test={len(X_test)}")
print(f"Emotion classes: {len(emotions_list)}, Gender classes: {len(gender_list)}, Speaker classes: {len(speaker_list)}")

def build_stable_cnn_lstm(shape, classes, filters=64):
    """بناء نموذج CNN-LSTM"""
    inp = Input(shape=shape)
    x = Conv2D(filters, kernel_size=(shape[0], 1), padding='valid', activation='relu')(inp)
    x = Reshape((shape[1], filters))(x)
    x = Conv1D(128, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = MaxPooling1D(pool_size=2)(x)
    x = Dropout(0.3)(x)
    x = Conv1D(128, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = MaxPooling1D(pool_size=2)(x)
    x = Dropout(0.3)(x)
    x = Bidirectional(LSTM(128))(x)
    x = Dropout(0.5)(x)
    x = Dense(128, activation="relu")(x)
    x = Dropout(0.5)(x)
    out = Dense(classes, activation="softmax")(x)
    model = Model(inp, out)
    return model

print("Model building function defined.")

import os
import numpy as np
import pandas as pd
import librosa
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import warnings
import kagglehub
import soundfile as sf
import gradio as gr

from tqdm import tqdm
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.utils.class_weight import compute_class_weight

from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Model
from tensorflow.keras.layers import *
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

warnings.filterwarnings("ignore")
print("TensorFlow:", tf.__version__)
print("All libraries imported successfully!")

# -*- coding: utf-8 -*-
"""Final Self-Contained Solution for Enhanced Model Training"""

!pip install audiomentations

from audiomentations import Compose, AddGaussianNoise, TimeStretch, PitchShift
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Layer
import tensorflow.keras.backend as K
from tqdm import tqdm
import librosa

def preprocess_and_augment_audio_internal(path, augment_data=False):
    augment = Compose([
        AddGaussianNoise(min_amplitude=0.001, max_amplitude=0.015, p=0.5),
        TimeStretch(min_rate=0.8, max_rate=1.25, p=0.5),
        PitchShift(min_semitones=-4, max_semitones=4, p=0.5),
    ])
    y, sr = librosa.load(path, sr=SAMPLE_RATE, duration=DURATION)
    y, _ = librosa.effects.trim(y)
    if np.max(np.abs(y)) > 0:
        y = y / np.max(np.abs(y))
    if augment_data:
        y = augment(samples=y, sample_rate=sr)
    target_len = int(SAMPLE_RATE * DURATION)
    if len(y) < target_len:
        y = np.pad(y, (0, target_len - len(y)))
    else:
        y = y[:target_len]
    return y, sr

def extract_features_from_signal_internal(y, sr):
    """
    Feature extraction for augmented audio
    MUST match extract_features() exactly
    """

    # ===== MFCC =====
    mfcc = librosa.feature.mfcc(
        y=y,
        sr=sr,
        n_mfcc=N_MFCC,
        hop_length=HOP_LENGTH
    )
    mfcc_d = librosa.feature.delta(mfcc)
    mfcc_dd = librosa.feature.delta(mfcc, order=2)

    # ===== Log-Mel =====
    mel = librosa.feature.melspectrogram(
        y=y,
        sr=sr,
        n_mels=N_MELS,
        hop_length=HOP_LENGTH,
        n_fft=N_FFT
    )
    logmel = librosa.power_to_db(mel)

    # ===== Chroma =====
    chroma = librosa.feature.chroma_stft(
        y=y,
        sr=sr,
        hop_length=HOP_LENGTH,
        n_fft=N_FFT
    )

    # ===== Spectral Contrast =====
    contrast = librosa.feature.spectral_contrast(
        y=y,
        sr=sr,
        hop_length=HOP_LENGTH,
        n_fft=N_FFT
    )

    # ===== Pitch =====
    pitch = librosa.yin(
        y,
        fmin=50,
        fmax=300,
        sr=sr
    )
    pitch = pitch.reshape(1, -1)

    # ===== Energy =====
    energy = librosa.feature.rms(
        y=y,
        hop_length=HOP_LENGTH
    )

    # ===== Stack all features =====
    features = np.vstack([
        mfcc,
        mfcc_d,
        mfcc_dd,
        logmel,
        chroma,
        contrast,
        pitch,
        energy
    ])

    return features


# --- Custom Attention Layer ---
class AttentionLayer(Layer):
    def __init__(self, **kwargs):
        super(AttentionLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.W = self.add_weight(name='att_weight', shape=(input_shape[-1], 1), initializer='normal')
        self.b = self.add_weight(name='att_bias', shape=(input_shape[1], 1), initializer='zeros')
        super(AttentionLayer, self).build(input_shape)

    def call(self, x):
        e = K.tanh(K.dot(x, self.W) + self.b)
        a = K.softmax(e, axis=1)
        output = x * a
        return K.sum(output, axis=1)

    def get_config(self):
        return super(AttentionLayer, self).get_config()

# --- Enhanced CNN-LSTM Model with Attention ---
def build_enhanced_cnn_lstm_attention(shape, classes, filters=64):
    inp = Input(shape=shape)
    x = Conv2D(filters, kernel_size=(shape[0], 1), padding='valid', activation='relu')(inp)
    x = Reshape((shape[1], filters))(x)
    x = Conv1D(128, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = MaxPooling1D(pool_size=2)(x)
    x = Dropout(0.3)(x)
    x = Conv1D(128, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = MaxPooling1D(pool_size=2)(x)
    x = Dropout(0.3)(x)
    x = Bidirectional(LSTM(128, return_sequences=True))(x) # return_sequences=True for attention
    x = AttentionLayer()(x) # Apply attention
    x = Dropout(0.5)(x)
    x = Dense(128, activation="relu")(x)
    x = Dropout(0.5)(x)
    out = Dense(classes, activation="softmax")(x)
    model = Model(inp, out)
    return model

def run_complete_enhanced_training(X_train, y_train_emotion_oh, paths_train, X_val, y_val_emotion_oh, scaler):
    """
    هذه الدالة تنفذ كل خطوات زيادة البيانات والتدريب في بيئة معزولة.
    """
    print("-- Starting Self-Contained Enhanced Training --")

    print("\nAugmenting training data...")
    augmented_features = []
    augmented_labels = []

    for i, path in enumerate(tqdm(paths_train)):
        try:
            y_audio, sr = preprocess_and_augment_audio_internal(path, augment_data=True)
            feat = extract_features_from_signal_internal(y_audio, sr)

            if feat.shape[1] < MAX_LEN:
                pad = MAX_LEN - feat.shape[1]
                feat = np.pad(feat, ((0,0),(0,pad)), mode='constant')
            else:
                feat = feat[:, :MAX_LEN]

            feat = feat.reshape(1, feat.shape[0], feat.shape[1], 1)
            feat_flat = feat.reshape(1, -1)
            feat_scaled = scaler.transform(feat_flat)
            feat_final = feat_scaled.reshape(feat.shape)


            processed_feat_shape = feat_final.squeeze(axis=0).shape
            if processed_feat_shape != X_train.shape[1:]:
              print(f"WARNING: Unexpected shape for processed feature: {processed_feat_shape} at index {i}")
              continue


            augmented_features.append(feat_final.squeeze(axis=0))
            augmented_labels.append(y_train_emotion_oh[i])

        except Exception as e:
            print(f"Could not augment file {path}: {e}")

    augmented_features = np.array(augmented_features)
    augmented_labels = np.array(augmented_labels)

    print(f"Original training data shape: {X_train.shape}")
    print(f"Augmented data shape: {augmented_features.shape}")

    X_train_combined = np.concatenate([X_train, augmented_features], axis=0)
    y_train_combined = np.concatenate([y_train_emotion_oh, augmented_labels], axis=0)

    shuffle_index = np.random.permutation(len(X_train_combined))
    X_train_shuffled = X_train_combined[shuffle_index]
    y_train_shuffled = y_train_combined[shuffle_index]

    print(f"Combined and shuffled training data shape: {X_train_shuffled.shape}")

    print("\n-- Training Enhanced Model on Augmented Data --")
    enhanced_emotion_model = build_enhanced_cnn_lstm_attention(X_train_shuffled.shape[1:], len(emotions_list))
    enhanced_emotion_model.compile(optimizer=Adam(learning_rate=5e-5), loss="categorical_crossentropy", metrics=["accuracy"])

    es = EarlyStopping(monitor="val_accuracy", patience=20, restore_best_weights=True, mode="max")
    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-7)

    history_enhanced = enhanced_emotion_model.fit(
        X_train_shuffled, y_train_shuffled,
        validation_data=(X_val, y_val_emotion_oh),
        epochs=150, batch_size=32,
        callbacks=[es, reduce_lr], verbose=1
    )
    def plot_training_curves(history, title="Training Curves"):
        plt.figure(figsize=(14, 5), dpi=DPI)

        # Accuracy
        plt.subplot(1, 2, 1)
        plt.plot(history.history["accuracy"], label="Train")
        plt.plot(history.history["val_accuracy"], label="Validation")
        plt.title("Model Accuracy")
        plt.xlabel("Epoch")
        plt.ylabel("Accuracy")
        plt.legend()

        # Loss
        plt.subplot(1, 2, 2)
        plt.plot(history.history["loss"], label="Train")
        plt.plot(history.history["val_loss"], label="Validation")
        plt.title("Model Loss")
        plt.xlabel("Epoch")
        plt.ylabel("Loss")
        plt.legend()

        plt.suptitle(title)
        plt.tight_layout()
        plt.show()
    # The plot_training_curves function was defined *inside* run_complete_enhanced_training,
    # but then called with `final_history` which was assigned *outside* this function.
    # Also, the call to `plot_training_curves` was not correctly indented to be part of the `run_complete_enhanced_training` function.
    # Moving the call outside, and passing `history_enhanced` as the `final_history` for now.
    # This part of the code needs review to ensure `final_history` and `final_model` are correctly returned/assigned.



    print("Enhanced emotion model training complete.")
    # ================= BEST ACCURACY SUMMARY =================

    # These variables are based on `final_history` which is not yet defined here.
    # Assuming `history_enhanced` is the intended history object.
    best_val_acc = max(history_enhanced.history["val_accuracy"])
    best_epoch = np.argmax(history_enhanced.history["val_accuracy"]) + 1

    best_train_acc = max(history_enhanced.history["accuracy"])

    print("\n===== TRAINING SUMMARY =====")
    print(f"Best Training Accuracy:     {best_train_acc * 100:.2f}%")
    print(f"Best Validation Accuracy:   {best_val_acc * 100:.2f}%")
    print(f"Achieved at Epoch:          {best_epoch}")
    return enhanced_emotion_model, history_enhanced # Return the model and history


try:
    final_model, final_history = run_complete_enhanced_training(
        X_train, y_train_emotion_oh, paths_train, X_val, y_val_emotion_oh, scaler
    )
    plot_training_curves(final_history, "Emotion Model Training Performance") # Call after final_history is available

    print("\n-- Final Evaluation --")
    loss, accuracy = final_model.evaluate(X_test, y_test_emotion_oh, verbose=0)
    print(f"Final Enhanced Test Accuracy: {accuracy * 100:.2f}%")

except NameError as e:
    print(f"Error: A required variable is not defined. Please make sure you have run the data splitting cell.")
    print(f"Missing variable details: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
    import traceback
    traceback.print_exc()

# -*- coding: utf-8 -*-
"""Training Gender and Speaker Models (Corrected)"""

# Import necessary callbacks
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau


es = EarlyStopping(monitor="val_accuracy", patience=15, restore_best_weights=True, mode="max")
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=1e-6)


print("\n--- Training Gender Model ---")
gender_model = build_stable_cnn_lstm(X_train.shape[1:], len(gender_list))
gender_model.compile(optimizer=Adam(learning_rate=1e-4), loss="binary_crossentropy", metrics=["accuracy"])

history_gender = gender_model.fit(
    X_train, y_train_gender_oh,
    validation_data=(X_val, y_val_gender_oh),
    epochs=50,
    batch_size=32,
    class_weight=dict(enumerate(compute_class_weight("balanced", classes=np.unique(y_train_gender), y=y_train_gender))),
    callbacks=[es, reduce_lr], # الآن سيعمل بدون مشاكل
    verbose=1
)
print("Gender model training complete.")


print("\n--- Training Speaker Model ---")
speaker_model = build_stable_cnn_lstm(X_train.shape[1:], len(speaker_list))
speaker_model.compile(optimizer=Adam(learning_rate=1e-4), loss="categorical_crossentropy", metrics=["accuracy"])

history_speaker = speaker_model.fit(
    X_train, y_train_speaker_oh,
    validation_data=(X_val, y_val_speaker_oh),
    epochs=80,
    batch_size=32,
    class_weight=dict(enumerate(compute_class_weight("balanced", classes=np.unique(y_train_speaker), y=y_train_speaker))),
    callbacks=[es, reduce_lr], # سيعمل هنا أيضاً
    verbose=1
)
print("Speaker model training complete.")

# =========================================================
#            MODEL EVALUATION & VISUALIZATION
#        (PASTEL THEME – 2 PLOTS PER ROW)
# =========================================================

print("Generating predictions on the test set...")

# ---------- Predictions ----------
pred_emotion_probs = final_model.predict(X_test)
pred_gender_probs = gender_model.predict(X_test)
pred_speaker_probs = speaker_model.predict(X_test)

pred_emotion_labels = np.argmax(pred_emotion_probs, axis=1)
pred_gender_labels = np.argmax(pred_gender_probs, axis=1)
pred_speaker_labels = np.argmax(pred_speaker_probs, axis=1)

# ---------- Classification Report ----------
from sklearn.metrics import classification_report

print("\n--- Emotion Classification Report (F1-score) ---")
print(
    classification_report(
        y_test_emotion,
        pred_emotion_labels,
        target_names=emotions_list
    )
)

# ---------- Accuracy Evaluation ----------
print("\n--- Model Accuracy on Test Set ---")

emotion_loss, emotion_acc = final_model.evaluate(X_test, y_test_emotion_oh, verbose=0)
gender_loss, gender_acc = gender_model.evaluate(X_test, y_test_gender_oh, verbose=0)
speaker_loss, speaker_acc = speaker_model.evaluate(X_test, y_test_speaker_oh, verbose=0)

print(f"Emotion Model Accuracy: {emotion_acc:.4f}")
print(f"Gender Model Accuracy:  {gender_acc:.4f}")
print(f"Speaker Model Accuracy: {speaker_acc:.4f}")

# =========================================================
#            CONFUSION MATRICES (ROW 1)
# =========================================================

def normalize_cm(cm):
    return cm.astype("float") / cm.sum(axis=1, keepdims=True)

cm_emotion = normalize_cm(confusion_matrix(y_test_emotion, pred_emotion_labels))
cm_gender  = normalize_cm(confusion_matrix(y_test_gender, pred_gender_labels))

fig, axes = plt.subplots(1, 2, figsize=(12, 5), dpi=130)

# Emotion CM
sns.heatmap(
    cm_emotion,
    ax=axes[0],
    annot=True,
    fmt=".2f",
    cmap="PuRd",          # pastel pink-purple
    cbar=False,
    linewidths=0.6,
    linecolor="white",
    xticklabels=emotions_list,
    yticklabels=emotions_list
)
axes[0].set_title("Emotion – Normalized Confusion Matrix")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("True")

# Gender CM
sns.heatmap(
    cm_gender,
    ax=axes[1],
    annot=True,
    fmt=".2f",
    cmap="BuPu",          # pastel blue-purple
    cbar=False,
    linewidths=0.6,
    linecolor="white",
    xticklabels=gender_list,
    yticklabels=gender_list
)
axes[1].set_title("Gender – Normalized Confusion Matrix")
axes[1].set_xlabel("Predicted")
axes[1].set_ylabel("True")

plt.tight_layout()
plt.show()

# =========================================================
#        SPEAKER CM + ACCURACY COMPARISON (ROW 2)
# =========================================================

fig, axes = plt.subplots(1, 2, figsize=(12, 5), dpi=130)

# ---------- Top-K Speaker Confusion Matrix ----------
top_speakers = np.unique(y_test_speaker)[:10]
mask = np.isin(y_test_speaker, top_speakers)

cm_speaker = confusion_matrix(
    y_test_speaker[mask],
    pred_speaker_labels[mask]
)

sns.heatmap(
    cm_speaker,
    ax=axes[0],
    cmap="RdPu",          # rose-pink
    annot=False,
    linewidths=0.5,
    linecolor="white"
)
axes[0].set_title("Speaker Confusion Matrix (Top 10)")
axes[0].set_xlabel("Predicted Speaker")
axes[0].set_ylabel("True Speaker")

# ---------- Accuracy Comparison ----------
model_names = ["Emotion", "Gender", "Speaker"]
accuracies = [emotion_acc, gender_acc, speaker_acc]
pastel_colors = ["#F4A7B9", "#B5C7E7", "#C3B1E1"]  # pink, baby blue, lavender

bars = axes[1].bar(
    model_names,
    accuracies,
    color=pastel_colors,
    edgecolor="#555555"
)

axes[1].set_title("Model Accuracy Comparison")
axes[1].set_ylabel("Accuracy")
axes[1].set_ylim(0, 1)

for bar in bars:
    height = bar.get_height()
    axes[1].text(
        bar.get_x() + bar.get_width() / 2,
        height + 0.02,
        f"{height:.2f}",
        ha="center",
        fontsize=10
    )

plt.tight_layout()
plt.show()

print("\nEvaluation complete. You can now run the GUI cell.")

def prepare_single(path):
    feat = extract_features(path)

    if feat.shape[1] < MAX_LEN:
        pad = MAX_LEN - feat.shape[1]
        feat = np.pad(feat, ((0, 0), (0, pad)), mode='constant')
    else:
        feat = feat[:, :MAX_LEN]

    feat = feat.reshape(1, feat.shape[0], feat.shape[1], 1)
    feat_flat = feat.reshape(1, -1)
    feat_scaled = scaler.transform(feat_flat)
    feat_final = feat_scaled.reshape(feat.shape)

    return feat_final


def predict_all(path):
    if path is None:
        return {"error": "Please upload an audio file!"}

    try:
        Xp = prepare_single(path)

        emo = final_model.predict(Xp, verbose=0)[0]
        gen = gender_model.predict(Xp, verbose=0)[0]
        spk = speaker_model.predict(Xp, verbose=0)[0]

        return {
            "emotion": emotions_list[np.argmax(emo)],
            "gender": gender_list[np.argmax(gen)],
            "speaker": f"Actor_{speaker_list[np.argmax(spk)]}",
        }

    except Exception as e:
        return {"error": f"Error processing audio: {str(e)}"}


def infer(audio):
    if audio is None:
        return {"error": "Please upload an audio file!"}
    return predict_all(audio)


# ================= Custom CSS (Gray Background + Centered Text) =================
custom_css = """
body {
    background-color:  #2b2f36;
}

.gradio-container {
    background-color: #E5E5E5;
}

#vocalbloom-desc {
    text-align: center;
    font-size: 22px;
    font-weight: 700;
    color: #db2777;
    margin-top: 12px;
    margin-bottom: 24px;
}

h1 {
    text-align: center;
    font-weight: 800;
    color: #1f2937;
}
"""

# ================= Gradio Theme =================
theme = gr.themes.Soft(
    primary_hue="pink",
    secondary_hue="purple",
    neutral_hue="gray",
    radius_size="lg",
    font=["Poppins", "Arial", "sans-serif"]
)

# ================= Gradio Interface =================
ui = gr.Interface(
    fn=infer,
    inputs=gr.Audio(type="filepath", label="🎧 Upload Audio"),
    outputs=gr.JSON(label="🌸 Predictions"),
    title="🌸🎧 VocalBloom",
    description=(
        "<div id='vocalbloom-desc'>"
        "VocalBloom is an intelligent speech emotion recognition system "
        "that analyzes vocal signals to identify human emotions "
        "in a simple and interactive way."
        "</div>"
    ),
    theme=theme,
    css=custom_css
)

ui.launch()